import streamlit as st
from openai import OpenAI

client = OpenAI(api_key="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")

# Set page title and favicon
st.set_page_config(page_title="AI Storyteller", page_icon="📖")

# Add a header and description
st.title("AI Storyteller")
st.markdown("This AI storyteller generates creative stories based on your prompts. Enter a prompt and select the emotion you want the story to convey. Click 'Generate Story' to see the magic!")

# User input for prompt and story title
user_input_prompt = st.text_area("Write a prompt for the AI storyteller:")
user_input_title = st.text_input("Enter a title for the story:")

# Dropdown for selecting emotion
emotion_options = ["Happy", "Sad", "Excited", "Mysterious", "Surprised"]
selected_emotion = st.selectbox("Select the emotion for the story:", emotion_options)

# Button to generate the story and images
if st.button("Generate Story and Images"):
    if user_input_prompt:
        try:
            # Modify the prompt based on the selected emotion
            prompt_with_emotion = f"Write a {selected_emotion.lower()} story: {user_input_prompt}"

            # Generate story using OpenAI GPT-3.5-turbo-instruct engine
            response = client.completions.create(
                model="gpt-3.5-turbo-instruct",
                prompt=prompt_with_emotion,
                max_tokens=500
            )

            # Display the generated story with title
            st.subheader(f"**{user_input_title}**")
            st.write(response.choices[0].text)

            # Use DALL·E to generate images based on the story
            image_response = client.images.generate(
                model="dall-e-2",
                prompt=user_input_title,  # Use the story title as the prompt for DALL·E
                n=5
            )

            # Display all the generated images in a column
            st.subheader("Generated Images:")
            for i, image_data in enumerate(image_response.data):
                image_url = image_data.url
                st.image(image_url, caption=f"Image {i + 1} generated by DALL·E", use_column_width=True)

        except Exception as e:
            st.error(f"An error occurred: {str(e)}")
    else:
        st.warning("Please enter a prompt for the AI storyteller.")

# Add a footer with attribution and link to OpenAI
st.markdown("---")
st.markdown("Built with ❤️ by Nexus")

# Add some styling to the app
st.markdown(
    """
    <style>
        body {
            color: #394240;
            background-color: #f5f5f5;
        }
        .st-bd {
            padding: 10px;
        }
    </style>
    """,
    unsafe_allow_html=True
)
